### PR TITLE
Reset linger on connection failure

### LINKED ISSUE #186: Reset linger on connection failed
When we get a `` `Connection_failed `` event we should reset the `linger` field so we don't carry over garbage to our next connection attempt.
https://github.com/robur-coop/miragevpn/blob/a5dca73bcb5c41fa8c357abd4f6d4832c22be72c/src/engine.ml#L1924-L1927

### PR DESCRIPTION
**Pull request by reynir**
This ensures we don't keep around partial packets from previous TCP connections. Fixes #186.

### CODE REVIEW

File: src/engine.ml [hunk 1]
```diff
@@ -1883,7 +1883,7 @@ let resolve_connect_client config ts s ev =
     | `Times m -> m > r
     | `Unlimited -> false
   in
-  let next_or_fail idx retry =
+  let next_or_fail t idx retry =
```
Comment (reynir) [inline src/engine.ml:1886]: Here we shadow `t`. The reason is because we return `next_or_fail`, and when it is called the state may have changed, at least judging from the structure of the code.

File: src/engine.ml [hunk 2]
```diff
@@ -1892,24 +1892,27 @@ let resolve_connect_client config ts s ev =
...
+            (Connecting (idx', ts, retry'), `Connect (ip, port, dp))
+      in
+      Ok ({ t with linger = Cstruct.empty; state = client state }, action)
   in
   match (s, ev) with
   | Resolving (idx, _, retry), `Resolved ip ->
       (* TODO enforce ipv4/ipv6 *)
       let endp = match remote idx with _, port, dp -> (ip, port, dp) in
-      Ok (Connecting (idx, ts, retry), Some (`Connect endp))
+      let t = { t with state = client (Connecting (idx, ts, retry)) } in
```
Comment (hannesm) [inline src/engine.ml:1908]: here we don't need to clean up the linger? I understand that the invariant we try to establish is that when we're in "connecting" state, there is no linger, is this correct?

Comment (reynir) [reply src/engine.ml:1908]: Yes, we want an invariant that when the state is `Connecting` (or `Resolving`) linger is empty.

**Comment by hannesm** [comment]
Overall, this looks good. I'm still hesitant in respect to passing partially applied functions around, since that makes the code harder to understand. On the other side, it removes code duplication.

We could (in a separate PR) push the "client_state" / "server_state" out of the record where it is combined with the keys... That may make the code easier to understand...

Feel free to merge, minor comments above.

File: src/engine.ml (hunk 2 above)
Comment (hannesm) [reply src/engine.ml:1908]: let's write that down somewhere then :)

File: src/engine.ml [hunk 3]
```diff
@@ -1869,7 +1869,7 @@ let retransmit timeout ts transport =
   in
   ({ transport with out_packets }, out)
 
-let resolve_connect_client config ts s ev =
+let resolve_connect_client client t config ts s ev =
```
[the remark this answers is not in the document]
Comment (reynir) [reply src/engine.ml]: I chose `make_state` as it makes a `state` out of a `client_state`.

File: src/engine.ml (hunk 1 above)
Comment (reynir) [reply src/engine.ml:1886]: Yes. It's not immediately obvious how to refactor `next_or_fail`. I arguably made things worse by passing `client` (now `make_client`) outside of the function(s) it's defined in.
